const quotes = [
  "Block party!",
  "No ads!",
  "Bye-bye, spam!",
  "Adios, ads!",
  "Get lost!",
  "Bye, trackers!",
  "Stop, right there!",
  "Catch you later!",
  "Ad free zone!",
  "Blockzilla strikes!",
  "Ad-ocalypse now!",
  "Nope, not today!",
  "Buzz off, ads!",
  "Ads? Not here!",
  "Shh... no ads.",
  "Ad blocker engaged!",
  "Gone in a click!",
  "Ads begone!",
  "Block mode: ON!",
  "Spam, who?",
  "No entry for ads!",
  "Bye-bye bandwidth hogs!",
  "Ad-free vibes!",
  "Don't block me!",
  "Not in my house!",
  "Get out, ads!",
  "Bye-bye popups!",
  "Say no to ads!",
  "Ad block, power!",
  "Stay adless!",
  "Access denied!",
  "Tracker blocked!",
  "No tracking zone!",
  "Rejected!",
  "Not welcome here!",
  "Request denied!",
  "Nice try, ads!",
  "Privacy shield up!",
  "Blocked by choice!",
  "Ad-free journey!",
  "Nothing to see!",
  "No soliciting!",
  "Request terminated!",
  "Traffic stopped!",
  "Privacy first!",
  "No way through!",
  "Blocked successfully!",
  "Shields activated!",
  "Look elsewhere!",
  "Access restricted!",
  "Stop tracking me!",
  "Blackholed!",
  "Sinkhole active!",
  "No ads allowed!",
  "Tracker neutralized!",
  "Request sunk!",
  "Bye data miners!",
  "Privacy protected!",
  "Tracking blocked!",
  "Not happening!"
];

export function GenerateQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)];
}
