FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git ca-certificates

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o goaway -ldflags="-X main.version=0.50.0 -X main.commit=ead2d7830add26d53ecab3c907a290f0cdc1e078 -X main.date=2025-04-11T13:37:56Z" .

FROM alpine:3.22

ARG DNS_PORT=6121
ARG WEBSITE_PORT=8080

ENV DNS_PORT=${DNS_PORT} WEBSITE_PORT=${WEBSITE_PORT}

RUN apk add --no-cache bash ca-certificates && \
    mkdir -p /app && \
    rm -rf /var/cache/apk/* /tmp/* /var/tmp/*

WORKDIR /app

COPY --from=builder /src/goaway ./goaway

COPY updater.sh ./

EXPOSE ${DNS_PORT}/tcp ${DNS_PORT}/udp ${WEBSITE_PORT}/tcp

ENTRYPOINT [ "./goaway" ]
