FROM ubuntu:22.04

ARG DNS_PORT=53
ARG WEBSITE_PORT=8080

ENV DNS_PORT=${DNS_PORT}
ENV WEBSITE_PORT=${WEBSITE_PORT}

RUN apt-get update && \
    apt-get install -y curl passwd jq git build-essential sudo

RUN curl -LO https://go.dev/dl/go1.23.3.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.23.3.linux-amd64.tar.gz && \
    rm go1.23.3.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

RUN useradd -m -s /bin/bash -G sudo appuser && \
    echo "appuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

WORKDIR /home/appuser

COPY . .

RUN go build -o /home/appuser/goaway -ldflags="-s -w -X main.version=0.21.0" main.go

COPY updater.sh /home/appuser/updater.sh
RUN chmod +x /home/appuser/updater.sh

RUN chown -R appuser:appuser /home/appuser

EXPOSE ${DNS_PORT}/tcp ${DNS_PORT}/udp ${WEBSITE_PORT}/tcp

USER appuser

CMD /home/appuser/goaway --dnsport=${DNS_PORT} --webserverport=${WEBSITE_PORT}
