FROM golang:1.25.1-alpine

WORKDIR /app

RUN mkdir -p /.cache && chmod 777 /.cache

RUN apk add --no-cache postgresql-client

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml", "-build.args_bin", "--dashboard=true"]
